### ISSUE TITLE
Error on start 20-wireguard.sh

### ISSUE THREAD

**Issue by matt08** [boostchicken-dev/udm-utilities#194]
**Describe the bug**
When I'm trying to run 20-wireguard.sh I get error:
```
# /mnt/data/on_boot.d/20-wireguard.sh
Error: you may only check for the existence of one container at a time
Error: error running container create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument
```

**To Reproduce**
1 .Make a directory for your keys and configuration:
`mkdir -p /mnt/data/wireguard`
2. Create your public and private keys:
```
podman run -i --rm --net=host --name wireguard_conf masipcat/wireguard-go wg genkey > /mnt/data/wireguard/privatekey
podman run -i --rm --net=host --name wireguard_conf masipcat/wireguard-go wg pubkey < /mnt/data/wireguard/privatekey > /mnt/data/wireguard/publickey
```
3. Create a Wireguard configuration in /mnt/data/wireguard

4. Copy 20-wireguard.sh to /mnt/data/on_boot.d and update its values to reflect your environment

5. Execute /mnt/data/on_boot.d/20-wireguard.sh

6. See error

**Expected behavior**
Wireguard start.

**Screenshots**
...

**UDM Information**
 - Dream Machine Pro
 - Firmware Version: 1.9.3
 - Controller Version: 6.2.25

**Additional context**
Boot script setup from [this](https://github.com/boostchicken/udm-utilities/tree/master/on-boot-script#steps) instruction.

**Comment by boostchicken** [comment]
can you paste me your script that is 20-wireguard?

**Comment by matt08** [comment]
@boostchicken :
```
ONTAINER=wireguard
# Starts a wireguard container that is deleted after it is stopped.
# All configs stored in /mnt/data/wireguard
if podman container exists ${CONTAINER}; then
  podman start ${CONTAINER}
else
  podman run -i -d --rm --net=host --name ${CONTAINER} --privileged \
    -v /mnt/data/wireguard:/etc/wireguard \
    -v /dev/net/tun:/dev/net/tun \
    -e LOG_LEVEL=info -e WG_COLOR_MODE=always \
    masipcat/wireguard-go:latest-arm64v8
fi
```

from [here](https://github.com/boostchicken/udm-utilities/blob/master/wireguard-go/on_boot.d/20-wireguard.sh)

**Comment by gtrabanco** [comment]
I had the same issue once but in my case was just starting the container because I have created the config outside of the UDM and upload it. The workaround for me was:

```bash
podman rm -v wireguard
/mnt/data/on_boot.d/20-wireguard.sh
```

In your case... you are using to create the keys the container `wireguard_conf` instead of `wireguard` try to use wireguard and post the result maybe the doc is not updated.
