### ISSUE TITLE
Add support for UXG-Pro

### ISSUE THREAD

**Issue by cainmp** [boostchicken-dev/udm-utilities#284]
I'd love to get support for at least some on-boot scripts to run, as well as the CNI network plugins for podman so I can run some containers

**Comment by boostchicken** [comment]
Podman support is here for the UDMPSE, you have to extract from the artifacts then install the cni plugins

https://github.com/boostchicken/udm-utilities/actions/runs/1538100885

**Comment by cainmp** [comment]
ok, so I was able to extract the ZIP file and place the results on my UXG, what do I need to do to install the plugins?

**Comment by boostchicken** [comment]
https://github.com/boostchicken-dev/udm-utilities/issues/356
