### ISSUE TITLE
Looking for new people willing to be codeownewrs to own and review directories in this this repo, its getting to be a lot of work for jsut me

### ISSUE THREAD

**Issue by boostchicken** [boostchicken-dev/udm-utilities#285]
If you feel you know a module well open up a PR to add yourself to .github/CODEOWNERS or ask me and I will do it.

**Comment by mazzy89** [comment]
As discussed you can redirect to me specific UDM PRO SE requests that can't be tested or made in the UDM PRO. willing to help.

**Comment by sundar2012** [comment]
do you have a discord?  whats the best forum to get in touch or ask questions (not bug related)?

**Comment by mazzy89** [comment]
We have a slack channel where you can ask questions or open a question in the discussions here on github

**Comment by sundar2012** [comment]
whats the slack channel?

**Comment by mazzy89** [comment]
Did you check the Readme? It is on the Readme 😎

**Comment by renedis** [comment]
@boostchicken i’m willing to help. If you can add me, please do.

**Comment by boostchicken** [comment]
hey everyone, there is a slack, it is not used much. So I made a discord.  @renedis  @mazzy89  @sundar2012, feel free to add yourself to the CODEOWNERS file via PR https://discord.gg/3gk4yHWyaf
