### ISSUE TITLE
Persistent Zerotier Bridge, /mnt/data/persistent/zerotier-one 

### ISSUE THREAD

**Issue by Slarty01** [boostchicken-dev/udm-utilities#303]
Hi Please is there a way I can get a bridge script to run using the 20Zerotier.sh script making it persistent, I'm trying to access all main VLAN's from Zerotier Remotely and all devices opposed to seeing one or two.  I see the risks involved but It would help me immensely.

I followed the instructions as well as I could and had the udmp running 1.11.0.3921 but after a restart it removed everything. I'm guessing (I'm the issue here) or is it that they have moved everything to the /mnt/data/persistent folder?

Any assistance welcomed

EDIT, Apologies it still is online, my bad erm I'm still figuring this out .. bit early at Christmas time.. I just need to figure out the Zerotier settings for the bridge setup hmmm

**Comment by jwronken** [comment]
Hi can you share your bridge script? I have ZT running in a podman container on the UDM-PRO but can't get the bridge to work?
Would really help me

**Comment by boostchicken** [comment]
@Slarty01 we would like your zero teir stuff :)

**Comment by Slarty01** [comment]
> @Slarty01 we would like your zero teir stuff :)

Mine doesn't exactly exist as yet i was aking more for a basic walk through apologies if it seemed somewhat naive and lacking in security. I was mearly hoping to use zerotier for the entire network
