### ISSUE TITLE
Documentation: podman network for DNS

### ISSUE THREAD

**Issue by dclobato** [boostchicken-dev/udm-utilities#309]
**Describe the bug**
The location specified for `20-dns.conflist` in `https://github.com/boostchicken-dev/udm-utilities/blob/master/run-pihole/README.md` does not work 

To make the DNS network, I had to run

```bash
podman network create dns
curl -L https://github.com/boostchicken-dev/udm-utilities/raw/master/cni-plugins/20-dns.conflist -o /etc/cni/net.d/dns.conflist
```
The rest of instructions were fine...

**UDM Information**
 - Dream Machine Pro
 - UniFi OS UDM Pro 1.11.0
 - Controller Version 6.5.55 (Build: atag_6.5.55_16678)

**Additional context**

**Comment by boostchicken** [comment]
on which file is this wrong?

**Comment by dclobato** [comment]
Created a pull request for this

**Comment by dclobato** [comment]
Done.

**Comment by trnitz** [comment]
This will only work until the UDM is rebooted, then the 'DNS' network will not come up.

The location of the *20-dns.conflict* file needs to be in **/mnt/data/podman/cni/dns.conflist**, not */etc/cni/net.d/dns.conflist*.


### Current instructions snippet ###

Well, these are the current instructions that work (until reboot).

The current steps, as of today, are out of order, as covered in [308](https://github.com/boostchicken-dev/udm-utilities/issues/308) and [309](https://github.com/boostchicken-dev/udm-utilities/issues/309).

- Download the *20-dns.conflist* file to */etc/cni/net.d/dns.conflist*

  ```
  curl -L https://github.com/boostchicken-dev/udm-utilities/raw/master/cni-plugins/20-dns.conflist -o /etc/cni/net.d/dns.conflist
  ```

- Execute the */mnt/data/on_boot.d/05-install-cni-plugins.sh* script.
  
- Create the *dns* network using `podman network create dns`

This works, until you reboot, as the */etc/cni/net.d/dns.conflist* file is wiped out on reboot, and the container fails to start as the network defined in the container doesn't exist.

### Correct instructions snippet ###

- Download the *20-dns.conflist* file to ***/mnt/data/podman/cni/dns.conflist***

  ```
  curl -L https://github.com/boostchicken-dev/udm-utilities/raw/master/cni-plugins/20-dns.conflist -o /mnt/data/podman/cni/dns.conflist
  ```

- Execute the */mnt/data/on_boot.d/05-install-cni-plugins.sh* script.
  
- Create the *dns* network using `podman network create dns`

## Explanation ##

The */etc/cni/net.d/dns.conflist* file is just symlink to */mnt/data/podman/cni/dns.conflist*

```
# ls -l /etc/cni/net.d/dns.conflist
lrwxrwxrwx    1 root     root            33 Feb 11 08:14 /etc/cni/net.d/dns.conflist -> /mnt/data/podman/cni/dns.conflist
```

In the */mnt/data/on_boot.d/05-install-cni-plugins.sh* script, the variable `CNI_NETD` set set to */mnt/data/podman/cni*, and then there is a function that creates the symlink:

```
populate_netd()
{
  for file in "${CNI_NETD}"/*.conflist
  do
    if [ -f "$file" ]; then
        ln -fs "$file" "/etc/cni/net.d/$(basename "$file")"
    fi
  done
}
```

If there the *dns.conflist* file doesn't exist in */mnt/data/podman/cni*, then no symlink is created, and then the *dns* network doesn't come up on bootup.

The quick "fix" is to back out [this](https://github.com/boostchicken-dev/udm-utilities/pull/324) update.
