### ISSUE TITLE
UDMPSE How to

### ISSUE THREAD

**Issue by janthony6** [boostchicken-dev/udm-utilities#310]
**Is your feature request related to a problem? Please describe.**
I can see how to install boost chicken utilities but I have no idea how to install Podman. Is there a guide for this? It says its required to be installed. 

**Describe the solution you'd like**
A guide so that I can use pbrah's wpa_supplicant bypass the way it worked on the UDMP

**Comment by mazzy89** [comment]
In the Readme is reported https://github.com/boostchicken-dev/udm-utilities#custom-podman-builds-for-udmp-se

It says to extract the zip file. This is enough to have Podman installed. Podman is distributed as a golang application so it's statically build and all the dependencies are bundled. No need to install anything more.

In case you would need more explanation please advice here what we should add in the Readme to make the process clearer

**Comment by dsbaars** [comment]
> In case you would need more explanation please advice here what we should add in the Readme to make the process clearer

I think it would be useful just to add the command how to unzip the file.

 `unzip podman-install.zip -d /`

Also the `podman-install.zip` was contained in the artifact (which is also a zip). 
That caused the podman-install.zip to be extracted to /.

**Comment by mazzy89** [comment]
Yes, we would need to fix this zip of the zipping at the GH level. Thanks for reporting.
