### ISSUE TITLE
Issues after update with podman, cannot access unifi-os shell

### ISSUE THREAD

**Issue by drentjess** [boostchicken-dev/udm-utilities#311]
**Describe the bug**
Hi all, I can't seem to get around the following error and really could use some help. I had everything up and running using your scripts (OnBootScripts and AdguardHome). After updating my UDM things broke down and now I am in the situation where I cannot access my unifi-os shell anymore and I get the following error when executing 'unifi-os shell'

/usr/sbin/unifi-os: line 331: podman: not found

Please help because I am not a great expert. I would really like to access unifi-os shell again and have my AdguardHome up and running again. 

**UDM Information**
 - Variant: Dream Machine
 - Firmware Version: 1.11.0.3921 (up to date)

**Comment by mikesrus** [comment]
read this https://github.com/boostchicken-dev/udm-utilities/issues/300 it helps for me back to stock podman
