### ISSUE TITLE
Unbound or similar with pi-hole

### ISSUE THREAD

**Issue by Montanadude** [boostchicken-dev/udm-utilities#314]
This is not problem but a request or maybe even an ask for help.
   I would like to be able to use unbound or similar with the pi-hole setup on my UDM-PRO so that
  I can see any and all urls in the logs.  This is in a home use situation with kids.  Is this possible?
  If not unbound ..maybe something similar as we know that pi-hole by itself is not a proxy so
 it is not possible as is.  

Thanks in advance

**Comment by gatesry** [comment]
I was able to get Unbound working, see my repo for the scripts https://github.com/gatesry/udm-lab/tree/main/packages/dns/unbound

Let me know if you have any questions!
