### ISSUE TITLE
UDM Pro SE installation of on_boot

### ISSUE THREAD

**Issue by jake-b** [boostchicken-dev/udm-utilities#316]
**Describe the bug**
The [remote-install.sh](https://raw.githubusercontent.com/boostchicken/udm-utilities/HEAD/on-boot-script/remote_install.sh) script does not properly install the usb-boot.service file on a USM Pro SE

**To Reproduce**
- Install the on-boot-script stuff using the `remote-install.sh` procedure
- spend some time wondering while it doesn't work
- then realize the contents of `/etc/systemd/system/udm-boot.service` is wrong

**Expected behavior**
- `/etc/systemd/system/udm-boot.service` is created properly

**Screenshots**
`/etc/systemd/system/udm-boot.service` is created with an ExecStart as follows:
```
bash -c 'mkdir -p /mnt/data/on_boot.d && find -L /mnt/data/on_boot.d -mindepth 1 -maxdepth 1 -type f -print0 | sort -z | xargs -0 -r -n 1 -- bash -c \'if test -x "/bin/sh"; then echo "%n: running /bin/sh"; "/bin/sh"; else case "/bin/sh" in *.sh) echo "%n: sourcing /bin/sh"; . "/bin/sh";; *) echo "%n: ignoring /bin/sh";; esac; fi\'
```
Note the `"/bin/sh"` parts that should be `$0`

**UDM Information**
 - Dream Machine Pro SE
 - UniFi OS UDM SE 2.3.11.6510

**Additional context**
my guess is just a few missing escapes and those $0's are being interpreted by the `install-remote.sh` script, rather than finding their way into the `udm-boot.service` file

**Comment by cryptk** [comment]
You just saved me a ton of time figuring out why my eap-proxy container wasn't starting up on boot on my UDMP-SE!  Thanks!

**Comment by daviddemacedo** [comment]
Thx a lot...you saved me a lot of time

**Comment by gtrabanco** [comment]
Sorry for the mistake, I haven't seen the issue.

Thanks @emilvissing for the pr.

Until the PR is approved you can install by using the fixed version by executing:

```bash
curl -fsL "https://raw.githubusercontent.com/emilvissing/udm-utilities/patch-1/on-boot-script/remote_install.sh" | /bin/sh
```

**Comment by boostchicken** [comment]
pr approved
