### ISSUE TITLE
PiHole on UDMPro - unexpected newline

### ISSUE THREAD

**Issue by andreasploetz** [boostchicken-dev/udm-utilities#319]
during execution of https://github.com/boostchicken-dev/udm-utilities/blob/master/cni-plugins/05-install-cni-plugins.sh [Step 2 from Installaton-Guide] i got the following error:

`# /mnt/data/on_boot.d/05-install-cni-plugins.sh
/mnt/data/on_boot.d/05-install-cni-plugins.sh: line 8: syntax error: unexpected newline
`
Am I doing something wrong?

**Comment by dadealus** [comment]
same here today on UDM Pro SE 

Ran the following 
root@UDMPSE:~# curl -fsL "https://raw.githubusercontent.com/boostchicken/u                                                                                           dm-utilities/HEAD/on-boot-script/remote_install.sh" | /bin/sh
  _   _ ___  __  __   ___           _
 | | | |   \|  \/  | | _ ) ___  ___| |_
 | |_| | |) | |\/| | | _ \/ _ \/ _ \  _|
  \___/|___/|_|  |_| |___/\___/\___/\__|

 Execute any script when your udm system
 starts.

UDR/UDMSE detected, installing on-boot script...
Failed to disable unit: Unit file udm-boot.service does not exist.
Creating systemctl service file
Enabling UDM boot...
Created symlink /etc/systemd/system/multi-user.target.wants/udm-boot.service → /                                                                                           etc/systemd/system/udm-boot.service.
UDM Boot Script installed

Downloading CNI plugins script...
CNI plugins script installed
Executing CNI plugins script...
Downloading https://github.com/containernetworking/plugins/releases/download/v1.                                                                                           0.1/cni-plugins-linux-arm64-v1.0.1.tgz.sha256
Downloading https://github.com/containernetworking/plugins/releases/download/v1.                                                                                           0.1/cni-plugins-linux-arm64-v1.0.1.tgz
Pouring /mnt/data/.cache/cni-plugins/cni-plugins-linux-arm64-v1.0.1.tgz

Downloading CNI bridge script...
CNI bridge script installed
Executing CNI bridge script...
/mnt/data/on_boot.d/06-cni-bridge.sh
/mnt/data/on_boot.d/06-cni-bridge.sh: 3: /mnt/data/on_boot.d/06-cni-bridge.sh: Syntax error: newline unexpected

On boot script installation finished

You can now place your scripts in `/mnt/data/on_boot.d`

**Comment by boostchicken** [comment]
weird i tested it locally and it works? how did you install it?

**Comment by boostchicken** [comment]
if you curl it make sure you curl the raw version https://raw.githubusercontent.com/boostchicken-dev/udm-utilities/master/cni-plugins/05-install-cni-plugins.sh

**Comment by boostchicken** [comment]
I just tested on my box, it works please make sure to use the raw URL if you are curling.
