### ISSUE TITLE
Suricata/podman bootloop

### ISSUE THREAD

**Issue by carlneuhaus** [boostchicken-dev/udm-utilities#338]
**Describe the bug**
While installing the Suricata upgrade (I know this is unsupported but wanted to raise awareness in case other podman script's are affected) I noticed a built in Unifi script that would read from /run/suricata.pid and KILL's the process relating to the PID.
The PID living at /run/suricata.pid seems to always be set to 1 as this is the PID the process has inside the podman container. This results in the Unifi script killing the process at PID 1 which relates to init and in turn reboots the system (leading to a bootloop).

**To Reproduce**
1. Install the Suricata update package and allow the scripts to start the container
2. View the file at /run/suricata.pid and observe it contains "1"
3. View the file /usr/share/ubios-udapi-server/ips/bin/getsig.sh at line  184 `SURIPID=$(cat /run/suricata.pid)` and line 185 `/bin/kill -SIGTERM "${SURIPID}"`
4. Error case can be forced by running `/usr/share/ubios-udapi-server/ips/bin/getsig.sh`. Output will displayed "IDS/IPS reload signal Sent"

**Expected behavior**
Unifi expects the PID living at /run/suricata.pid to be the PID of Suricata however due to the program running in a container it is always set to PID=1

**UDM Information**
 - Dream Machine Pro
 - UniFi OS Version v1.11.4

**Comment by boostchicken** [comment]
I would upgrade your firmware. the latest suricata version there is higher.
