### ISSUE TITLE
[run-pihole] Update results in error "no space left on device"

### ISSUE THREAD

**Issue by simkin** [boostchicken-dev/udm-utilities#352]
**Describe the bug**
Update of running pihole container results in error "no space left on device"

**To Reproduce**
1. Execute: https://github.com/boostchicken-dev/udm-utilities/blob/master/run-pihole/upd_pihole.sh

**UDM Information**
- UDM-SE
- UniFi OS UDM SE 2.3.15
- 7.0.25 (Build: atag_7.0.25_17292)

**Additional context**
root@UDM-SE:/mnt/data/scripts# ./upd_pihole.sh
```
Trying to pull docker.io/pihole/pihole:latest...
Getting image source signatures
Copying blob 4f4fb700ef54 skipped: already exists
Copying blob 2203022c5aa9 skipped: already exists
Copying blob 06779f18ab1d done
Copying blob e12c43fd1d43 done
Copying blob bcc0395f729f done
Copying blob 56b3a064f5b3 done
Copying blob 2c6ae85afe38 done
Copying blob 0353d8b31ee2 done
Copying blob f8cdbf9a46bd done
Error: writing blob: adding layer with blob "sha256:0353d8b31ee2e9b93acba6bfde248175d28342eb3edb7bcfe58c1faeff4bfa73": error creating layer with ID "bcec34788c022a84d4840e080c666994285fd94c7b1fa373eb2f898bac914509": no space left on device
pihole
d9741bdf361d8822d03d135b9b5c970607f91bf9611dc39b28dfe3e5c33c26df
d5c915d135e56ab23450adef2bc02b7618ab9f5bc98c086893112596a9c73cb3
```

root@UDM-SE:/mnt/data/scripts# df -h
```
Filesystem                         Size  Used Avail Use% Mounted on
udev                               2.0G     0  2.0G   0% /dev
tmpfs                              395M   34M  362M   9% /run
/dev/disk/by-partlabel/root        2.0G  1.4G  419M  78% /boot/firmware
/dev/loop0                         732M  732M     0 100% /mnt/.rofs
/dev/disk/by-partlabel/overlay     5.4G  5.2G     0 100% /mnt/.rwfs
overlayfs-root                     5.4G  5.2G     0 100% /
/dev/disk/by-partlabel/data        3.9G   29M  3.7G   1% /data
/dev/disk/by-partlabel/log         976M   69M  841M   8% /var/log
/dev/disk/by-partlabel/persistent  2.0G  186M  1.7G  11% /persistent
tmpfs                              2.0G  108K  2.0G   1% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs                              1.0G  136K  1.0G   1% /tmp
/dev/sda5                          109G  605M  103G   1% /ssd1
tmpfs                               64M  5.2M   59M   8% /var/opt/unifi/tmp
tmpfs                              512M     0  512M   0% /var/opt/unifi-protect/tmp
shm                                 63M     0   63M   0% /var/lib/containers/storage/vfs-containers/15b57bf3f479d6892dbb6ff07d115c621ea6724d19e8f07474c397dd17ce21f4/userdata/shm
shm                                 63M  1.2M   62M   2% /var/lib/containers/storage/vfs-containers/d5c915d135e56ab23450adef2bc02b7618ab9f5bc98c086893112596a9c73cb3/userdata/shm
```

**Comment by alxwolf** [comment]
Suggest you check what takes up all the space in `/data`

One assumption is that you have unused container images lying around.

Run `podman image ls`.

This will give you (next to tons of errors) a listing like this
```
REPOSITORY                    TAG       IMAGE ID       CREATED         SIZE                       R/O
docker.io/pihole/pihole       latest    4834a75f9450   2 weeks ago     302 MB                     false
docker.io/klutchell/unbound   latest    fa6c0b948e15   3 weeks ago     13.7 MB                    false
localhost/unifi-os            default   8d87405a1cb5   2 months ago    1.58 GB                    true
localhost/unifi-os            latest    8d87405a1cb5   2 months ago    1.58 GB                    true
localhost/unifi-os            current   6c3ea197b84b   2 months ago    unable to determine size   false
docker.io/neilpang/acme.sh    latest    a01b581157a2   3 months ago    28.9 MB                    false
docker.io/library/golang      1.17.3    cfa41b175271   4 months ago    827 MB                     false
```

Then run `podman image rm cfa41b175271` (with the IMAGE ID you want to delete) to free up the space again.

**Comment by simkin** [comment]
Somehow my pi image was huge and contained both a logfile and a .db file of nearly 6 GB large. I deleted it and now everything is good (but for how long?) Is that normal/expected? (I am a new pihole user)

**Comment by alxwolf** [comment]
Yes, that is another potential storage eater (had the same issue...)

pi-hole uses two log files / databases:
`/var/log/pihole.log` *in the container* should not be an issue at it gets rotated by log rotate every midnight.

`/data/pihole/etc-pihole/pihole-FTL.db` can break your back (and that was probably the case).

Fix (what I did) is either to:

Edit `/data/pihole/etc-pihole/pihole-FTL.conf`, and modify or create an entry 
```
MAXDBDAYS=30
```

This value [MAXDBDAYS](https://docs.pi-hole.net/ftldns/configfile/#maxdbdays) defaults to 365 (days) and configures how long DNS queries will be stored in the local database. Choose `30` or less, that should still be enough for most use cases. `0` will turn the database off, but not delete existing entries

Restart the container, and new setting will be applied.

Or: 

add `-e MAXDBDAYS=30 \` to the `upd_pihole.sh` script.

**Comment by simkin** [comment]
Thank you, will do that. I am surprised I stumbled on this issue after 24h already :/ Maybe I by accident enabled debug logging. Will monitor and adapt!

**Comment by alxwolf** [comment]
Well one small mistake: must be `FTLCONF_MAXDBDAYS` in the docker / podmann call.

**Comment by alxwolf** [comment]
With 70 clients my "30 day limited" log file has about 200MB. Just as an indication.
