### ISSUE TITLE
udm boot script install, missing dependancy

### ISSUE THREAD

**Issue by iloominaty** [boostchicken-dev/udm-utilities#355]
**Describe the bug**
install script not working, missing "ubnt-device-info" dependancy.

**To Reproduce**
1. Run "remote_install.sh" script found [HERE](https://github.com/boostchicken-dev/udm-utilities/blob/master/on-boot-script/README.md)

**Expected behavior**
I expect the script to complete without errors

**Actuall behavior**
```
root@ubnt:/# curl -fsL "https://raw.githubusercontent.com/boostchicken-dev/udm-utilities/HEAD/on-boot-script/remote_install.sh" | /bin/sh
  _   _ ___  __  __   ___           _
 | | | |   \|  \/  | | _ ) ___  ___| |_
 | |_| | |) | |\/| | | _ \/ _ \/ _ \  _|
  \___/|___/|_|  |_| |___/\___/\___/\__|

 Execute any script when your udm system
 starts.

Missing dependencie(s): `ubnt-device-info`
```

**UDM Information**
 -  UDM
 - UniFi OS Version 1.11.4
 - Network Version 7.0.25

**Comment by alxwolf** [comment]
please issue `ubnt-device-info` directly on your UDM. 

If that works, please try `ubnt-device-info summary` and post result (anonymising the MAC address).

**Comment by iloominaty** [comment]
Hi sorry, i forgot to mention that i already tried that.

```
root@ubnt:/# ubnt-device-info
bash: ubnt-device-info: command not found
root@ubnt:/#
```

**Comment by iloominaty** [comment]
im so sorry

I was in the unifi-os shell when attempting to run the script...

Please disregard everything.
Again, sorry.

**Comment by alxwolf** [comment]
not that this did not happen to me before :) 

When UDM/P reaches the same SW level as the UDM SE, this part will be over...

**Comment by iceman3k** [comment]
I would like my cloud key gen 2+ to have the on_boot function and am receiving this error. Is it possible to get persistent scripts and packages on the cloud key gen 2+? Running UniFi OS 3.2.7. Thanks!
