### ISSUE TITLE
onboot not launching my script

### ISSUE THREAD

**Issue by merryprankster02** [boostchicken-dev/udm-utilities#360]
I apologize because i am new to this. I went through the installation and placed my script in mnt/data/onboot.d and made it executable but it is still not launching on boot. 

here is the contents of my script 99-run-vpn.sh:

#!/bin/sh
rm -f /etc/split-vpn
ln -sf /mnt/data/split-vpn /etc/split-vpn
/etc/split-vpn/run-vpn.sh

I have tested that the script works without error if i manually launch it. Where can i look to see why it isnt launching on boot?

**Comment by gatesry** [comment]
While someone here might have more insight. The split-vpn project is maintained by peacy @ https://github.com/peacey/split-vpn

You might have better success asking over there.

**Comment by merryprankster02** [comment]
i dont think the issue is with splitvpn because the script runs fine if run manually. it just isnt being called called, i can tell because it doesnt even create a log file.

**Comment by merryprankster02** [comment]
thanks, was able to figure this out. for some reason the install script was not enable on installation. 

root@ubnt:/# systemctl status udm-boot
● udm-boot.service - Run On Startup UDM
   Loaded: loaded (/lib/systemd/system/udm-boot.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

once it was enabled and started it persists after reboot
