### ISSUE TITLE
run-pihole README.md Issues

### ISSUE THREAD

**Issue by stuartofmt** [boostchicken-dev/udm-utilities#366]
**Describe the bug**
The Readme.md for run-pihole is difficult to use.
There are some contradictory instructions and some of the explanations are unclear.
This can lead to an unsuccessful install.

Attached is a suggested rewrite:

**Comment by stuartofmt** [comment]
Fixed some editing :-)

[README.md](https://github.com/boostchicken-dev/udm-utilities/files/8691456/README.md)

**Comment by stuartofmt** [comment]
One thing that is unclear:   Should there be a `podman network create dns`  before / after step 2.3 ?

The reason is that after my first unsuccessful attemp (following the original instructions) - I was unable to "undo" everything.  In particular the version of podman did not allow removal of the dns network.  Its a bit "old and cranky".

I found through experimentation that changing  /etc/cni/net.d/dns.conflist changed the podman network definitions (including changing the name of the network).  Clearly they are tightly coupled.

So its unclear to me if the creation of  /etc/cni/net.d/dns.conflist creates the podman network in the first instance or if the explicit podman command is needed initially.

**Comment by DavidBurela** [comment]
I found the pihole readme unclear, and discovered I did it wrong the first time. 
I had started to do my own rewrite to submit, but then found your rewrite in this Issue which is already great.

Maybe submit it as a PR instead, and link to this issue. That might help get it accepted quicker.

**Comment by stuartofmt** [comment]
Good suggestion.  PR submitted.

**Comment by boostchicken** [comment]
How dare you all critique my writing.  :) PR merged, thanks for contributing :)

**Comment by stuartofmt** [comment]
I'd prefer not to think of it as critiquing your writing but instead as improving our reading :-)

Thanks for all your effort in providing this.  Glad I could, in some small way, help.
