### ISSUE TITLE
UDM-SE Podman artifact expired

### ISSUE THREAD

**Issue by manselmi** [boostchicken-dev/udm-utilities#378]
**Describe the bug**
The most recent UDM-SE Podman artifact has expired.

**To Reproduce**
1. Visit https://github.com/boostchicken-dev/udm-utilities/actions/workflows/podman-udmse.yml
2. Click on the most recent workflow run [Merge pull request #332 from JohannLange/master](https://github.com/boostchicken-dev/udm-utilities/actions/runs/2014794526)
3. Observe that the `udmse-podman-install.zip` artifact has expired.

**Expected behavior**
The most recent UDM-SE Podman artifact should always be available to download, regardless of when the corresponding GitHub action was last triggered.

**Screenshots**
<img width="1028" alt="Screen Shot 2022-06-19 at 11 01 22 PM" src="https://user-images.githubusercontent.com/8533952/174518173-15725839-0107-4a09-a760-9d3b1b1d0908.png">

**UDM Information**
 - Variant: UDM-SE
 - Firmware Version: UniFi OS UDM SE 2.4.10
 - Controller Version: Network 7.1.66

**Comment by boostchicken** [comment]
Running them now

**Comment by boostchicken** [comment]
Ill work on a better setup for this

**Comment by nachtien** [comment]
Hey @boostchicken, it's expired again :).  Thanks for creating this!

**Comment by adrienvsj** [comment]
I confirm @boostchicken, it's expired again. Thank you for your help !

**Comment by adrienvsj** [comment]
@nachtien I recreated it myself by forking the repository and restarting the build. You can access it here : https://github.com/adrienvsj/unifios-utilities/actions/workflows/podman-udmse.yml
